In [1]:
import numpy as np
import pandas as pd

use = pd.read_excel(
    "../data/raw/io/IOUse_After_Redefinitions_PRO_Detail.xlsx",
    sheet_name="2017",
    skiprows=[0,1,2,3]
)

make = pd.read_excel(
    "../data/raw/io/IOMake_After_Redefinitions_PRO_Detail.xlsx",
    sheet_name="2017",
    skiprows=[0,1,2,3]
)

In [2]:
make.head()

,Industry / Commodity,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Other federal government enterprises,State and local government (educational services),State and local government (hospitals and health services),State and local government (other services),Other state and local government enterprises,Scrap,Used and secondhand goods,Noncomparable imports,Rest of the world adjustment,Total Industry Output
0,Code,Industry Description,1111A0,1111B0,111200.0,111300.0,111400.0,111900.0,112120.0,1121A0,...,S00102,GSLGE,GSLGH,GSLGO,S00203,S00401,S00402,S00300,S00900,T008
1,1111A0,Oilseed farming,37922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38216
2,1111B0,Grain farming,NaN,57259,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57882
3,111200,Vegetable and melon farming,NaN,NaN,18582.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18806
4,111300,Fruit and tree nut farming,NaN,NaN,NaN,29731.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29958

In [3]:
new_cols = make.columns.astype(str) + "_" + make.iloc[0].astype(str)
make.cols=new_cols
make= make.iloc[1:].reset_index(drop=True)

/tmp/ipykernel_467713/3369136407.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  make.cols=new_cols

In [4]:
make.head()

,Industry / Commodity,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Other federal government enterprises,State and local government (educational services),State and local government (hospitals and health services),State and local government (other services),Other state and local government enterprises,Scrap,Used and secondhand goods,Noncomparable imports,Rest of the world adjustment,Total Industry Output
0,1111A0,Oilseed farming,37922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38216
1,1111B0,Grain farming,NaN,57259,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57882
2,111200,Vegetable and melon farming,NaN,NaN,18582.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18806
3,111300,Fruit and tree nut farming,NaN,NaN,NaN,29731.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29958
4,111400,"Greenhouse, nursery, and floriculture production",NaN,NaN,NaN,NaN,19840.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20064

In [5]:
V =make.iloc[:,2:].fillna(0).values.astype(int)

/tmp/ipykernel_467713/1866238292.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  V =make.iloc[:,2:].fillna(0).values.astype(int)

In [6]:
V.shape

(403, 403)

In [7]:
V

array([[   37922,        0,        0, ...,        0,        0,    38216],
       [       0,    57259,        0, ...,        0,        0,    57882],
       [       0,        0,    18582, ...,        0,        0,    18806],
       ...,
       [       0,        0,        0, ...,        0,        0,    63412],
       [       0,        0,        0, ...,        0,        0,   273909],
       [   37922,    57259,    18582, ...,        0,     3468, 34468130]],
      shape=(403, 403))

In [8]:
q = V[-1,:-1]

In [9]:
q

array([  37922,   57259,   18582,   29731,   19868,   24875,   38106,
         87445,   44165,   33237,   21325,    9239,   29718,  212664,
         27801,   11688,   15627,   14477,   14883,   28579,   89691,
        455762,   80214,   80967,   47123,  101181,  204428,   84468,
        169386,   79772,  252295,   70668,  123210,  123629,  270471,
        143054,   35953,   23986,   21939,   25216,    8352,   26227,
          8070,   30655,    6104,   12480,    8067,    4724,    4943,
          4070,    6179,    5103,  101973,    9247,    8816,   25546,
         15472,   19930,   10561,   16493,   12324,    6712,   13042,
         10943,    8756,   43306,   41400,    6971,    8055,   17580,
          8728,    5645,   37044,   29110,   26122,    4470,   24115,
          5983,    5949,   13063,   13901,   24691,    7392,   32074,
         16946,   14325,   24425,    4553,    1179,   18358,    4384,
         32793,    5836,    6385,   10307,    7601,    8384,   12065,
          3031,    4936,   26159,    8892,   17400,   28500,    3001,
          6731,    2561,   22650,   10655,    8156,    4119,    8074,
          5265,   25918,    4617,   50455,   18510,   25321,   31310,
         49918,    2857,   10342,    5136,   11229,   15534,    8962,
         12002,    3097,    1927,    1381,   11520,    3311,   20478,
          5205,    8965,   11163,   10662,    7434,    1982,   11261,
         12979,    3299,   10755,   32781,  215421,   29382,   10556,
         10606,    6185,   16179,   38178,   23963,   41482,   30523,
         35554,   61210,   25339,  134840,   43359,   40746,   17616,
          7324,   12655,   24878,   10214,    7230,    5876,    7917,
         14403,   11814,    3829,    4646,    3256,    7305,   18714,
         10062,   39162,   28837,    4291,    6785,    4866,    9378,
          9648,    2207,    3169,   10202,   25864,   23089,   30795,
         15154,   13236,    9946,   30215,    9529,   38002,   32322,
         39658,   42587,   21566,   41308,    7321,   67787,  149079,
         13836,   52406,   23678,   39283,   13325,   11780,   22242,
         31959,   45168,   32126,   21346,   19090,   61142,    3279,
         10568,    8557,    9612,    3938,    9850,   11586,    4963,
          7436,   36462,   32235,   62202,   20795,    6223,   12030,
          4543,   64488,    4410,  478145,   13168,   10571,   27852,
         63437,    9709,    6678,   33613,  117608,   88537,   19890,
         11136,  152158,   13372,   31287,   17142,   15045,   27121,
         15213,   36904,   37955,    4286,   40929,   40136,   17757,
          4529,    8934,   10600,   11115,   98254,   18847,    5931,
         17350,  136107,  206450,  221877,  168866,  287826,  199853,
        181062,  161947,  384877,   47545,   38513,  301799,  236806,
        227348,  142940,  119517,   89954,  138827,  281220,  230453,
        231562,   78668,   53010,  339147,   95611,   50196,  155764,
        112649,  128619,   13501,   13989,   37042,   11933,  233075,
        131377,   18727,   81710,   22500,  368097,  227512,   33671,
        248108,   56921,   10603,  346710,  633605,  389244,  162725,
         90314,  583848,  370207,  186494, 1553178,  467675, 1291178,
        140524,  111204,   31741,  158260,  354236,  271583,  197262,
         60313,  178669,  340173,  203314,   57833,  616844,  405537,
         37602,   12827,   39409,   88662,  551870,  384086,  189379,
         38077,   33602,   92400,   57742,   70078,   34737,  133156,
         53010,  248764,   79242,  492093,  129400,   98044,  166141,
         55128,  107602,   36283, 1053801,  190100,   54157,  112901,
         58404,   55383,   46511,   46235,   39400,   32661,   21226,
         18091,  112145,   86072,  236913,  373564,  384984,  188002,
        194285,   50441,   64098,   55139,   79630,   21338,   29195,
         81336,  100202,   58458,   95191,   18684,  599358,  379143,
         69564,    1233,  832472,   68698,  836043,  107059,   10763,
             0,       0,    3468])

In [10]:
qden = q + (q==0)*1

In [11]:
D = V[:-1, :-1] @ np.diag( 1 / qden)

In [12]:
D.sum(axis=0)

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.00003009,
       1.        , 1.        , 1.00003365, 0.9999953 , 1.        ,
       1.        , 1.        , 1.        , 1.00006719, 0.99996501,
       1.        , 1.        , 1.        , 0.99998765, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.99995442, 1.        ,
       0.99976054, 1.00003813, 1.        , 0.99996738, 0.99983617,
       1.        , 1.        , 1.        , 1.        , 1.0002457 ,
       1.        , 1.        , 1.        , 1.00010814, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.99991886, 0.99985101, 0.99984665, 0.99990862, 0.99977159,
       0.99997691, 0.99992754, 0.99985655, 0.99987585, 1.        ,
       0.99988543, 0.99982285, 1.        , 0.9999313 , 1.        ,
       1.        , 0.99991706, 1.00016714, 0.9998319 , 1.        ,
       0.99964031, 0.9999595 , 0.99986472, 0.99996882, 1.00005901,
       0.99993019, 1.        , 1.        , 1.00084818, 1.        ,
       0.9997719 , 1.        , 1.        , 1.        , 0.99970894,
       0.99973688, 0.99988073, 1.00008288, 1.00032992, 1.        ,
       1.00003823, 0.99977508, 1.00005747, 0.99985965, 1.00033322,
       1.        , 1.        , 0.9999117 , 0.99990615, 0.99987739,
       0.99975722, 0.99962844, 1.00018993, 0.99992283, 1.        ,
       1.        , 0.99994598, 1.00003949, 1.        , 1.00002003,
       0.99964998, 0.99990331, 1.        , 0.99991094, 1.00006437,
       0.99988842, 0.99991668, 1.        , 1.00051894, 0.99927589,
       1.00008681, 1.        , 0.9998535 , 1.        , 1.        ,
       0.99991042, 0.99990621, 1.        , 1.        , 1.0000888 ,
       1.        , 1.        , 1.00009298, 1.        , 1.        ,
       1.        , 0.99990527, 1.00009429, 1.        , 0.99993819,
       1.        , 1.        , 1.        , 1.        , 0.99997187,
       0.99998366, 0.99996054, 0.99999258, 1.00002306, 0.99992637,
       1.        , 1.00013654, 1.        , 0.9999598 , 0.9999021 ,
       1.00013831, 0.99982982, 0.99974738, 1.        , 1.        ,
       1.        , 0.99956952, 1.        , 1.00013689, 0.99994656,
       0.99970185, 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.9996801 , 0.9997927 , 0.9995469 , 0.99968444,
       1.00009802, 0.99996134, 1.        , 1.        , 1.00006599,
       1.00007555, 0.99989946, 1.0000331 , 1.00020989, 1.        ,
       0.99996906, 1.        , 1.00002348, 1.        , 1.00002421,
       1.        , 1.00001475, 1.00001342, 0.99992772, 1.        ,
       1.        , 1.00002546, 1.        , 1.        , 0.99995504,
       0.99993742, 0.99995572, 1.00003113, 1.00004685, 1.        ,
       1.        , 1.        , 0.99990537, 1.00023373, 0.99989596,
       1.        , 0.99979695, 1.        , 1.00020149, 1.        ,
       0.99994515, 1.        , 0.99998392, 0.99985573, 0.99983931,
       0.99991687, 0.99977988, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.999897  ,
       0.99985025, 0.999881  , 0.99998299, 0.99998871, 1.        ,
       1.0000898 , 1.        , 1.        , 0.99996804, 1.00011667,
       1.00006647, 1.        , 0.99993427, 1.0000271 , 0.99997365,
       1.        , 1.00002443, 1.00002492, 0.99983105, 1.        ,
       1.00011193, 0.99990566, 1.        , 1.00001018, 1.        ,
       1.00016861, 0.99988473, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.00001046, 1.        , 0.99999358, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.00000761, 1.        , 1.        , 0.99995556,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.00000615,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.99999632, 1.        , 1.00001658,
       1.        , 0.99999706, 1.00000492, 0.99998271, 1.        ,
       0.99999753, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.99998918, 1.        , 1.        , 1.00002879, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.00000929, 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.99998288,
       1.00001806, 1.        , 1.00002163, 1.        , 1.        ,
       1.        , 0.99994472, 1.        , 0.99998838, 1.        ,
       1.        , 1.        , 0.99999468, 1.        , 1.        ,
       0.9999844 , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.99998949, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.99981418, 0.        ,
       0.        , 1.        ])

In [13]:
A = D @ B

NameError: name 'B' is not defined

In [14]:
A.shape

NameError: name 'A' is not defined

In [16]:
L = np.linalg.inv(np.eye(402) - A)

NameError: name 'A' is not defined

In [17]:
mults = L.sum(axis=0)

NameError: name 'L' is not defined

In [17]:
mults

NameError: name 'mults' is not defined

In [18]:
mults.max()

NameError: name 'mults' is not defined

In [19]:
mults.min()

NameError: name 'mults' is not defined

In [20]:
mults[0:4]

NameError: name 'mults' is not defined

In [262]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,Code,Commodity Description,1111A0,1111B0,111200.0,111300.0,111400.0,111900.0,112120.0,1121A0,...,F07C00,F07E00,F07N00,F07S00,F10C00,F10E00,F10N00,F10S00,T004,T007
1,1111A0,Oilseed farming,8332,455,40.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9796,37922
2,1111B0,Grain farming,NaN,7694,NaN,NaN,NaN,446.0,1697.0,4253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7666,57259
3,111200,Vegetable and melon farming,NaN,NaN,666.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13231,18582
4,111300,Fruit and tree nut farming,NaN,NaN,NaN,748.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10167,29731

In [269]:
E = use.iloc[1:,405:].fillna(0)

In [270]:
E

,Personal consumption expenditures,Nonresidential private fixed investment in equipment,Nonresidential private fixed investment in intellectual property products,Residential private fixed investment,Nonresidential private fixed investment in structures,Change in private inventories,Exports of goods and services,Imports of goods and services,Federal Government defense: Consumption expenditures,Federal national defense: Gross investment in equipment,...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
1,0,0,0,0,0,-1330,12088,-963,0,0,...,0,0,0,0,0,0,0,0,9796,37922
2,2483,0,0,0,0,-2056,8886,-1647,0,0,...,0,0,0,0,0,0,0,0,7666,57259
3,19881,0,0,0,0,-673,2426,-8403,0,0,...,0,0,0,0,0,0,0,0,13231,18582
4,24499,0,0,0,0,-758,5750,-19324,0,0,...,0,0,0,0,0,0,0,0,10167,29731
5,13189,0,0,0,0,84,710,-2688,0,0,...,0,0,0,0,0,0,0,0,11295,19868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
405,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
407,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
408,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [274]:
E.values[-6:]

array([[13290625, 1159953, 906246, 773891, 594900, 32674, 2082977,
        -2626305, 599358, 77264, 63714, 7956, 379143, 19195, 109261,
        10161, 1737213, 44204, 44768, 304902, 19612103, 34468130],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=object)

In [68]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,Code,Commodity Description,1111A0,1111B0,111200.0,111300.0,111400.0,111900.0,112120.0,1121A0,...,F07C00,F07E00,F07N00,F07S00,F10C00,F10E00,F10N00,F10S00,T004,T007
1,1111A0,Oilseed farming,8332,455,40.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9796,37922
2,1111B0,Grain farming,NaN,7694,NaN,NaN,NaN,446.0,1697.0,4253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7666,57259
3,111200,Vegetable and melon farming,NaN,NaN,666.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13231,18582
4,111300,Fruit and tree nut farming,NaN,NaN,NaN,748.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10167,29731

In [69]:
new_cols = use.columns.astype(str) + "_" + use.iloc[0].astype(str)

In [70]:
use.cols=new_cols
use= use.iloc[1:].reset_index(drop=True)

/tmp/ipykernel_11359/726143188.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  use.cols=new_cols

In [86]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,1111A0,Oilseed farming,8332.0,455.0,40.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9796.0,37922.0
1,1111B0,Grain farming,0.0,7694.0,0.0,0.0,0.0,446.0,1697.0,4253.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7666.0,57259.0
2,111200,Vegetable and melon farming,0.0,0.0,666.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13231.0,18582.0
3,111300,Fruit and tree nut farming,0.0,0.0,0.0,748.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10167.0,29731.0
4,111400,"Greenhouse, nursery, and floriculture production",0.0,0.0,0.0,0.0,2640.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11295.0,19868.0

In [87]:
use.shape

(408, 427)

In [72]:
use.iloc[:,2:] = (use.iloc[:,2:].apply(pd.to_numeric, errors='coerce').fillna(0.0))

In [73]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,1111A0,Oilseed farming,8332.0,455.0,40.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9796.0,37922.0
1,1111B0,Grain farming,0.0,7694.0,0.0,0.0,0.0,446.0,1697.0,4253.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7666.0,57259.0
2,111200,Vegetable and melon farming,0.0,0.0,666.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13231.0,18582.0
3,111300,Fruit and tree nut farming,0.0,0.0,0.0,748.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10167.0,29731.0
4,111400,"Greenhouse, nursery, and floriculture production",0.0,0.0,0.0,0.0,2640.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11295.0,19868.0

In [74]:
use.tail(10)

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
398,S00401,Scrap,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-19722.0,10763.0
399,S00402,Used and secondhand goods,0.0,0.0,0.0,0.0,-18.0,0.0,0.0,0.0,...,0.0,-4.0,0.0,-2683.0,0.0,-14497.0,0.0,3909.0,-27562.0,0.0
400,S00300,Noncomparable imports,111.0,371.0,0.0,0.0,0.0,0.0,181.0,172.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-142489.0,0.0
401,S00900,Rest of the world adjustment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3468.0,3468.0
402,T005,Total Intermediate,20547.0,48075.0,10655.0,11723.0,9659.0,17494.0,28922.0,60750.0,...,379143.0,19195.0,109261.0,10161.0,1737213.0,44204.0,44768.0,304902.0,19612103.0,34468130.0
403,V00100,Compensation of employees,1062.0,3149.0,2497.0,5182.0,5551.0,4823.0,2179.0,1231.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
404,V00200,"Taxes on production and imports, less subsidies",1112.0,-8237.0,489.0,826.0,362.0,-41.0,853.0,1890.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
405,V00300,Gross operating surplus,15495.0,14896.0,5165.0,12227.0,4492.0,4298.0,6583.0,24181.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
406,T006,Total Value Added,17670.0,9807.0,8151.0,18235.0,10405.0,9081.0,9616.0,27302.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
407,T008,Total Industry Output,38216.0,57882.0,18806.0,29958.0,20064.0,26575.0,38538.0,88052.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
list(use.columns.values)

['Commodities/Industries',
 'Unnamed: 1',
 'Oilseed farming',
 'Grain farming',
 'Vegetable and melon farming',
 'Fruit and tree nut farming',
 'Greenhouse, nursery, and floriculture production',
 'Other crop farming',
 'Dairy cattle and milk production',
 'Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming',
 'Poultry and egg production',
 'Animal production, except cattle and poultry and eggs',
 'Forestry and logging',
 'Fishing, hunting and trapping',
 'Support activities for agriculture and forestry',
 'Oil and gas extraction',
 'Coal mining',
 'Copper, nickel, lead, and zinc mining',
 'Iron, gold, silver, and other metal ore mining',
 'Stone mining and quarrying',
 'Other nonmetallic mineral mining and quarrying',
 'Drilling oil and gas wells',
 'Other support activities for mining',
 'Electric power generation, transmission, and distribution',
 'Natural gas distribution',
 'Water, sewage and other systems',
 'Health care structures',
 'Educational and vocational structures',
 'Nonresidential maintenance and repair',
 'Residential maintenance and repair',
 'Office and commercial structures',
 'Multifamily residential structures',
 'Other residential structures',
 'Manufacturing structures',
 'Other nonresidential structures',
 'Power and communication structures',
 'Single-family residential structures',
 'Transportation structures and highways and streets',
 'Sawmills and wood preservation',
 'Veneer, plywood, and engineered wood product manufacturing',
 'Millwork',
 'All other wood product manufacturing',
 'Clay product and refractory manufacturing',
 'Glass and glass product manufacturing',
 'Cement manufacturing',
 'Ready-mix concrete manufacturing',
 'Concrete pipe, brick, and block manufacturing',
 'Other concrete product manufacturing',
 'Lime and gypsum product manufacturing',
 'Abrasive product manufacturing',
 'Cut stone and stone product manufacturing',
 'Ground or treated mineral and earth manufacturing',
 'Mineral wool manufacturing',
 'Miscellaneous nonmetallic mineral products',
 'Iron and steel mills and ferroalloy manufacturing',
 'Steel product manufacturing from purchased steel',
 'Secondary smelting and alloying of aluminum',
 'Alumina refining and primary aluminum production',
 'Aluminum product manufacturing from purchased aluminum',
 'Nonferrous metal (except aluminum) smelting and refining',
 'Copper rolling, drawing, extruding and alloying',
 'Nonferrous metal (except copper and aluminum) rolling, drawing, extruding and alloying',
 'Ferrous metal foundries',
 'Nonferrous metal foundries',
 'Custom roll forming',
 'All other forging, stamping, and sintering',
 'Metal crown, closure, and other metal stamping (except automotive)',
 'Cutlery and handtool manufacturing',
 'Plate work and fabricated structural product manufacturing',
 'Ornamental and architectural metal products manufacturing',
 'Power boiler and heat exchanger manufacturing',
 'Metal tank (heavy gauge) manufacturing',
 'Metal can, box, and other metal container (light gauge) manufacturing',
 'Hardware manufacturing',
 'Spring and wire product manufacturing',
 'Machine shops',
 'Turned product and screw, nut, and bolt manufacturing',
 'Coating, engraving, heat treating and allied activities',
 'Plumbing fixture fitting and trim manufacturing',
 'Valve and fittings other than plumbing',
 'Ball and roller bearing manufacturing',
 'Fabricated pipe and pipe fitting manufacturing',
 'Ammunition, arms, ordnance, and accessories manufacturing',
 'Other fabricated metal manufacturing',
 'Farm machinery and equipment manufacturing',
 'Lawn and garden equipment manufacturing',
 'Construction machinery manufacturing',
 'Mining and oil and gas field machinery manufacturing',
 'Semiconductor machinery manufacturing',
 'Other industrial machinery manufacturing',
 'Optical instrument and lens manufacturing',
 'Photographic and photocopying equipment manufacturing',
 'Other commercial and service industry machinery manufacturing',
 'Heating equipment (except warm air furnaces) manufacturing',
 'Air conditioning, refrigeration, and warm air heating equipment manufacturing',
 'Industrial and commercial fan and blower and air purification equipment manufacturing',
 'Industrial mold manufacturing',
 'Special tool, die, jig, and fixture manufacturing',
 'Machine tool manufacturing',
 'Cutting and machine tool accessory, rolling mill, and other metalworking machinery manufacturing',
 'Turbine and turbine generator set units manufacturing',
 'Speed changer, industrial high-speed drive, and gear manufacturing',
 'Mechanical power transmission equipment manufacturing',
 'Other engine equipment manufacturing',
 'Air and gas compressor manufacturing',
 'Measuring, dispensing, and other pumping equipment manufacturing',
 'Material handling equipment manufacturing',
 'Power-driven handtool manufacturing',
 'Packaging machinery manufacturing',
 'Industrial process furnace and oven manufacturing',
 'Other general purpose machinery manufacturing',
 'Fluid power process machinery',
 'Electronic computer manufacturing',
 'Computer storage device manufacturing',
 'Computer terminals and other computer peripheral equipment manufacturing',
 'Telephone apparatus manufacturing',
 'Broadcast and wireless communications equipment',
 'Other communications equipment manufacturing',
 'Semiconductor and related device manufacturing',
 'Printed circuit assembly (electronic assembly) manufacturing',
 'Other electronic component manufacturing',
 'Electromedical and electrotherapeutic apparatus manufacturing',
 'Search, detection, and navigation instruments manufacturing',
 'Automatic environmental control manufacturing',
 'Industrial process variable instruments manufacturing',
 'Totalizing fluid meter and counting device manufacturing',
 'Electricity and signal testing instruments manufacturing',
 'Analytical laboratory instrument manufacturing',
 'Irradiation apparatus manufacturing',
 'Watch, clock, and other measuring and controlling device manufacturing',
 'Audio and video equipment manufacturing',
 'Manufacturing and reproducing magnetic and optical media',
 'Electric lamp bulb and part manufacturing',
 'Lighting fixture manufacturing',
 'Small electrical appliance manufacturing',
 'Major household appliance manufacturing',
 'Power, distribution, and specialty transformer manufacturing',
 'Motor and generator manufacturing',
 'Switchgear and switchboard apparatus manufacturing',
 'Relay and industrial control manufacturing',
 'Storage battery manufacturing',
 'Primary battery manufacturing',
 'Communication and energy wire and cable manufacturing',
 'Wiring device manufacturing',
 'Carbon and graphite product manufacturing',
 'All other miscellaneous electrical equipment and component manufacturing',
 'Automobile manufacturing',
 'Light truck and utility vehicle manufacturing',
 'Heavy duty truck manufacturing',
 'Motor vehicle body manufacturing',
 'Truck trailer manufacturing',
 'Motor home manufacturing',
 'Travel trailer and camper manufacturing',
 'Motor vehicle gasoline engine and engine parts manufacturing',
 'Motor vehicle electrical and electronic equipment manufacturing',
 'Motor vehicle transmission and power train parts manufacturing',
 'Motor vehicle seating and interior trim manufacturing',
 'Motor vehicle metal stamping',
 'Other motor vehicle parts manufacturing',
 'Motor vehicle steering, suspension component (except spring), and brake systems manufacturing',
 'Aircraft manufacturing',
 'Aircraft engine and engine parts manufacturing',
 'Other aircraft parts and auxiliary equipment manufacturing',
 'Guided missile and space vehicle manufacturing',
 'Propulsion units and parts for space vehicles and guided missiles',
 'Railroad rolling stock manufacturing',
 'Ship building and repairing',
 'Boat building',
 'Motorcycle, bicycle, and parts manufacturing',
 'Military armored vehicle, tank, and tank component manufacturing',
 'All other transportation equipment manufacturing',
 'Wood kitchen cabinet and countertop manufacturing',
 'Upholstered household furniture manufacturing',
 'Nonupholstered wood household furniture manufacturing',
 'Institutional furniture manufacturing',
 'Other household nonupholstered furniture',
 'Showcase, partition, shelving, and locker manufacturing',
 'Office furniture and custom architectural woodwork and millwork manufacturing',
 'Other furniture related product manufacturing',
 'Surgical and medical instrument manufacturing',
 'Surgical appliance and supplies manufacturing',
 'Dental equipment and supplies manufacturing',
 'Ophthalmic goods manufacturing',
 'Dental laboratories',
 'Jewelry and silverware manufacturing',
 'Sporting and athletic goods manufacturing',
 'Doll, toy, and game manufacturing',
 'Office supplies (except paper) manufacturing',
 'Sign manufacturing',
 'All other miscellaneous manufacturing',
 'Dog and cat food manufacturing',
 'Other animal food manufacturing',
 'Flour milling and malt manufacturing',
 'Wet corn milling',
 'Fats and oils refining and blending',
 'Soybean and other oilseed processing',
 'Breakfast cereal manufacturing',
 'Sugar and confectionery product manufacturing',
 'Frozen food manufacturing',
 'Fruit and vegetable canning, pickling, and drying',
 'Cheese manufacturing',
 'Dry, condensed, and evaporated dairy product manufacturing',
 'Fluid milk and butter manufacturing',
 'Ice cream and frozen dessert manufacturing',
 'Poultry processing',
 'Animal (except poultry) slaughtering, rendering, and processing',
 'Seafood product preparation and packaging',
 'Bread and bakery product manufacturing',
 'Cookie, cracker, pasta, and tortilla manufacturing',
 'Snack food manufacturing',
 'Coffee and tea manufacturing',
 'Flavoring syrup and concentrate manufacturing',
 'Seasoning and dressing manufacturing',
 'All other food manufacturing',
 'Soft drink and ice manufacturing',
 'Breweries',
 'Wineries',
 'Distilleries',
 'Tobacco manufacturing',
 'Fiber, yarn, and thread mills',
 'Fabric mills',
 'Textile and fabric finishing and fabric coating mills',
 'Carpet and rug mills',
 'Curtain and linen mills',
 'Other textile product mills',
 'Apparel manufacturing',
 'Leather and allied product manufacturing',
 'Pulp mills',
 'Paper mills',
 'Paperboard mills',
 'Paperboard container manufacturing',
 'Paper bag and coated and treated paper manufacturing',
 'Stationery product manufacturing',
 'Sanitary paper product manufacturing',
 'All other converted paper product manufacturing',
 'Printing',
 'Support activities for printing',
 'Petroleum refineries',
 'Asphalt paving mixture and block manufacturing',
 'Asphalt shingle and coating materials manufacturing',
 'Other petroleum and coal products manufacturing',
 'Petrochemical manufacturing',
 'Industrial gas manufacturing',
 'Synthetic dye and pigment manufacturing',
 'Other basic inorganic chemical manufacturing',
 'Other basic organic chemical manufacturing',
 'Plastics material and resin manufacturing',
 'Synthetic rubber and artificial and synthetic fibers and filaments manufacturing',
 'Medicinal and botanical manufacturing',
 'Pharmaceutical preparation manufacturing',
 'In-vitro diagnostic substance manufacturing',
 'Biological product (except diagnostic) manufacturing',
 'Fertilizer manufacturing',
 'Pesticide and other agricultural chemical manufacturing',
 'Paint and coating manufacturing',
 'Adhesive manufacturing',
 'Soap and cleaning compound manufacturing',
 'Toilet preparation manufacturing',
 'Printing ink manufacturing',
 'All other chemical product and preparation manufacturing',
 'Plastics packaging materials and unlaminated film and sheet manufacturing',
 'Plastics pipe, pipe fitting, and unlaminated profile shape manufacturing',
 'Laminated plastics plate, sheet (except packaging), and shape manufacturing',
 'Polystyrene foam product manufacturing',
 'Urethane and other foam product (except polystyrene) manufacturing',
 'Plastics bottle manufacturing',
 'Other plastics product manufacturing',
 'Tire manufacturing',
 'Rubber and plastics hoses and belting manufacturing',
 'Other rubber product manufacturing',
 'Motor vehicle and motor vehicle parts and supplies',
 'Professional and commercial equipment and supplies',
 'Household appliances and electrical and electronic goods',
 'Machinery, equipment, and supplies',
 'Other durable goods merchant wholesalers',
 "Drugs and druggists' sundries",
 'Grocery and related product wholesalers',
 'Petroleum and petroleum products',
 'Other nondurable goods merchant wholesalers',
 'Wholesale electronic markets and agents and brokers',
 'Customs duties',
 'Motor vehicle and parts dealers',
 'Food and beverage stores',
 'General merchandise stores',
 'Building material and garden equipment and supplies dealers',
 'Health and personal care stores',
 'Gasoline stations',
 'Clothing and clothing accessories stores',
 'Nonstore retailers',
 'All other retail',
 'Air transportation',
 'Rail transportation',
 'Water transportation',
 'Truck transportation',
 'Transit and ground passenger transportation',
 'Pipeline transportation',
 'Scenic and sightseeing transportation and support activities',
 'Couriers and messengers',
 'Warehousing and storage',
 'Newspaper publishers',
 'Periodical Publishers',
 'Book publishers',
 'Directory, mailing list, and other publishers',
 'Software publishers',
 'Motion picture and video industries',
 'Sound recording industries',
 'Radio and television broadcasting',
 'Cable and other subscription programming',
 'Wired telecommunications carriers',
 'Wireless telecommunications carriers (except satellite)',
 'Satellite, telecommunications resellers, and all other telecommunications',
 'Data processing, hosting, and related services',
 'Internet publishing and broadcasting and Web search portals',
 'News syndicates, libraries, archives and all other information services',
 'Nondepository credit intermediation and related activities',
 'Monetary authorities and depository credit intermediation',
 'Other financial investment activities',
 'Securities and commodity contracts intermediation and brokerage',
 'Direct life insurance carriers',
 'Insurance carriers, except direct life',
 'Insurance agencies, brokerages, and related activities',
 'Funds, trusts, and other financial vehicles',
 'Owner-occupied housing',
 'Tenant-occupied housing',
 'Other real estate',
 'Automotive equipment rental and leasing',
 'Commercial and industrial machinery and equipment rental and leasing',
 'General and consumer goods rental',
 'Lessors of nonfinancial intangible assets',
 'Legal services',
 'Custom computer programming services',
 'Computer systems design services',
 'Other computer related services, including facilities management',
 'Accounting, tax preparation, bookkeeping, and payroll services',
 'Architectural, engineering, and related services',
 'Management consulting services',
 'Environmental and other technical consulting services',
 'Scientific research and development services',
 'Advertising, public relations, and related services',
 'Specialized design services',
 'Photographic services',
 'Veterinary services',
 'All other miscellaneous professional, scientific, and technical services',
 'Management of companies and enterprises',
 'Employment services',
 'Services to buildings and dwellings',
 'Office administrative services',
 'Facilities support services',
 'Business support services',
 'Travel arrangement and reservation services',
 'Investigation and security services',
 'Other support services',
 'Waste management and remediation services',
 'Elementary and secondary schools',
 'Junior colleges, colleges, universities, and professional schools',
 'Other educational services',
 'Offices of physicians',
 'Offices of dentists',
 'Offices of other health practitioners',
 'Outpatient care centers',
 'Medical and diagnostic laboratories',
 'Home health care services',
 'Other ambulatory health care services',
 'Hospitals',
 'Nursing and community care facilities',
 'Residential mental health, substance abuse, and other residential care facilities',
 'Individual and family services',
 'Child day care services',
 'Community food, housing, and other relief services, including vocational rehabilitation services',
 'Performing arts companies',
 'Spectator sports',
 'Independent artists, writers, and performers',
 'Promoters of performing arts and sports and agents for public figures',
 'Museums, historical sites, zoos, and parks',
 'Amusement parks and arcades',
 'Gambling industries (except casino hotels)',
 'Other amusement and recreation industries',
 'Accommodation',
 'Full-service restaurants',
 'Limited-service restaurants',
 'All other food and drinking places',
 'Automotive repair and maintenance (including car washes)',
 'Electronic and precision equipment repair and maintenance',
 'Commercial and industrial machinery and equipment repair and maintenance',
 'Personal and household goods repair and maintenance',
 'Personal care services',
 'Death care services',
 'Dry-cleaning and laundry services',
 'Other personal services',
 'Religious organizations',
 'Grantmaking, giving, and social advocacy organizations',
 'Civic, social, professional, and similar organizations',
 'Private households',
 'Federal general government (defense)',
 'Federal general government (nondefense)',
 'Postal service',
 'Federal electric utilities',
 'Other federal government enterprises',
 'State and local government (educational services)',
 'State and local government (hospitals and health services)',
 'State and local government (other services)',
 'State and local government passenger transit',
 'State and local government electric utilities',
 'Other state and local government enterprises',
 'Total Intermediate',
 'Personal consumption expenditures',
 'Nonresidential private fixed investment in equipment',
 'Nonresidential private fixed investment in intellectual property products',
 'Residential private fixed investment',
 'Nonresidential private fixed investment in structures',
 'Change in private inventories',
 'Exports of goods and services',
 'Imports of goods and services',
 'Federal Government defense: Consumption expenditures',
 'Federal national defense: Gross investment in equipment',
 'Federal national defense: Gross investment in intellectual property products',
 'Federal national defense: Gross investment in structures',
 'Federal Government nondefense: Consumption expenditures',
 'Federal nondefense: Gross investment in equipment',
 'Federal nondefense: Gross investment in intellectual property products',
 'Federal nondefense: Gross investment in structures',
 'State and local government consumption expenditures',
 'State and local: Gross investment in equipment',
 'State and local: Gross investment in intellectual property products',
 'State and local: Gross investment in structures',
 'Total Final Uses (GDP)',
 'Total Commodity Output']

In [84]:
use.iloc[0:2,403] # 403 is last industry

0    0.0
1    0.0
Name: Other state and local government enterprises, dtype: object

In [88]:
use.shape

(408, 427)

In [146]:
g = use.iloc[407,2:404] # total industry output
g

Oilseed farming                                                38216.0
Grain farming                                                  57882.0
Vegetable and melon farming                                    18806.0
Fruit and tree nut farming                                     29958.0
Greenhouse, nursery, and floriculture production               20064.0
                                                                ...
State and local government (hospitals and health services)    309771.0
State and local government (other services)                   866778.0
State and local government passenger transit                   16928.0
State and local government electric utilities                  63412.0
Other state and local government enterprises                  273909.0
Name: 407, Length: 402, dtype: object

In [147]:
g = g.astype(int)

In [148]:
g

Oilseed farming                                                38216
Grain farming                                                  57882
Vegetable and melon farming                                    18806
Fruit and tree nut farming                                     29958
Greenhouse, nursery, and floriculture production               20064
                                                               ...
State and local government (hospitals and health services)    309771
State and local government (other services)                   866778
State and local government passenger transit                   16928
State and local government electric utilities                  63412
Other state and local government enterprises                  273909
Name: 407, Length: 402, dtype: int64

In [195]:
q = use.iloc[0:402, -1].astype(int).values # total commodity output

In [196]:
q[-10:]

array([ 69564,   1233, 832472,  68698, 836043, 107059,  10763,      0,
            0,   3468])

In [197]:
g.sum()

np.int64(34468137)

In [198]:
q.sum()

np.int64(34468138)

In [199]:
U = use.iloc[0:402, 2:404].astype(int)

In [200]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,1111A0,Oilseed farming,8332.0,455.0,40.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9796.0,37922.0
1,1111B0,Grain farming,0.0,7694.0,0.0,0.0,0.0,446.0,1697.0,4253.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7666.0,57259.0
2,111200,Vegetable and melon farming,0.0,0.0,666.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13231.0,18582.0
3,111300,Fruit and tree nut farming,0.0,0.0,0.0,748.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10167.0,29731.0
4,111400,"Greenhouse, nursery, and floriculture production",0.0,0.0,0.0,0.0,2640.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11295.0,19868.0

In [201]:
U.shape

(402, 402)

In [202]:
g.shape

(402,)

In [203]:
gden = g + (g==0)
gden = gden.values

In [204]:
gden.shape

(402,)

In [205]:
U.shape

(402, 402)

In [206]:
U.sum(axis=0)

Oilseed farming                                                20547
Grain farming                                                  48070
Vegetable and melon farming                                    10654
Fruit and tree nut farming                                     11717
Greenhouse, nursery, and floriculture production                9659
                                                               ...
State and local government (hospitals and health services)    155507
State and local government (other services)                   333166
State and local government passenger transit                   26997
State and local government electric utilities                  33922
Other state and local government enterprises                  148806
Length: 402, dtype: int64

In [207]:
B = U @ np.diag(1/gden)

In [208]:
B.sum(axis=0)

0      0.537654
1      0.830483
2      0.566521
3      0.391114
4      0.481409
         ...
397    0.502006
398    0.384373
399    1.594813
400    0.534946
401    0.543268
Length: 402, dtype: float64

In [209]:
Bsum = B.sum(axis=0)

In [210]:
Bsum.sort_values()

390    0.000000
278    0.000000
311    0.022953
321    0.055989
110    0.109267
         ...
54     0.874443
319    0.899600
193    0.917673
395    1.354485
399    1.594813
Length: 402, dtype: float64

In [211]:
U.shape

(402, 402)

In [212]:
U = U.values

In [213]:
U[:,395]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
         15,    0,    0,    0,    0,    0,    0,    0,    0,    0,  138,
        136,  112,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    3,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    1,    4,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    1,    0,    0,   46,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,   66,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    2,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,  109,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,   15,    0,    0,    0,    0,    5,   58,  144,   84,
          2,    7,   19,   33,  170,   24,   14,    2,   19,   16,    8,
         34,   18,   15,   99,    0,    7,    0,    0,    0,    0,    0,
          0,    3,    6,    0,    0,    0,    1,    0,    0,    0,    0,
          0,    1,    0,  112,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          5,    0,    0,    0,    0,    0,    0,    0,    0,    0,   26,
          0,    0,    0,   10,    7,    1,    9,   21,    8,  101,   46,
        100,    3,    0,    0,    0,    0,    0,    0,    1,    0,    0,
          0,   62,    6,    0,   35,   11,    2,    0,    6,    0,    0,
          0,    3,   29,    0,    0,   70,  218,    0,  274,   34,  135,
        355,    0,  111,  430,   23,    0,    0,    0,   99, 3337,    0,
          0,    0,   68,   93,   72,    0,   15,    0,    0,    0,   50,
         38,   54,    0,    0,    0,  174,   32,    0,    0,    0,    0,
         91,   27,    0,    0,    5,    0,    4,    1,   24,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    4,    0,    0,    0,    0,    0,    0,
         40,   13,    7,   20,    0,  387,    0,    0,    0,    0,    0,
          0,    0,    0,    2,    0,    0,    0,   61,    0,    0,    0,
          0,    0,    0,    0,    0,    0])

In [214]:
use.iloc[0,[395, 399]]

Postal service                                                0.0
State and local government (hospitals and health services)    0.0
Name: 0, dtype: object

In [219]:
g.iloc[[395, 399]] # these have negative value added

Other federal government enterprises             6209
State and local government passenger transit    16928
Name: 407, dtype: int64

In [48]:
use.iloc[6][use.iloc[6]=='S00203']

Series([], Name: 6, dtype: object)

In [46]:
17670+20547

38217

In [42]:
flows

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 417,Unnamed: 418,Unnamed: 419,Unnamed: 420,Unnamed: 421,Unnamed: 422,Unnamed: 423,Unnamed: 424,Unnamed: 425,Unnamed: 426
5,8332,455,40,NaN,NaN,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9796,37922
6,NaN,7694,NaN,NaN,NaN,446,1697,4253,1597,175,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7666,57259
7,NaN,NaN,666,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13231,18582
8,NaN,NaN,NaN,748,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10167,29731
9,NaN,NaN,NaN,NaN,2640,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11295,19868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,1062,3149,2497,5182,5551,4823,2179,1231,2521,2793,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,1112,-8237,489,826,362,-41,853,1890,1051,985,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,15495,14896,5165,12227,4492,4298,6583,24181,2239,19371,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,17670,9807,8151,18235,10405,9081,9616,27302,5812,23149,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
412,38216,57882,18806,29958,20064,26575,38538,88052,44568,33443,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN